apiVersion: v2
name: cloudpirates-common
description: A library chart for common templates and helper functions, forked from CloudPirates GmbH & Co. KG
type: library
version: 2.1.0
appVersion: "2.1.0"
sources:
  - https://github.com/cisco-ai-defense/ai-defense-hybrid/tree/main/charts/cloudpirates-common
annotations:
  license: Apache-2.0