{{- if and .Values.config.content (not .Values.config.existingConfigmap)}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-config
  namespace: {{ include "redis.namespace" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  {{- if (include "redis.annotations" .) }}
  annotations:
{{- include "redis.tplvalues.render" (dict "value" (include "redis.annotations" .) "context" .) | indent 4 }}
  {{- end }}
data:
  redis.conf: |
    {{- .Values.config.content | nindent 4 }}
    # Port Configuration
    port {{ .Values.service.port }}
    # Disable RDB persistence
    save ""
{{- end }}