{{ if .Values.global.replicated.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  # Note: Do not use "replicated" for the name of the pull secret
  name: {{ (index .Values.global.imagePullSecrets 0).name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.replicated.dockerconfigjson }}
{{ end }}