apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ include "redis.namespace" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  {{- $annotations := merge .Values.service.annotations .Values.commonAnnotations }}
  {{- if $annotations }}
  annotations:
{{ include "redis.tplvalues.render" (dict "value" $annotations "context" .) | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
    {{- range .Values.extraPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .name }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}