apiVersion: v2
name: redis
description: An open source, in-memory data structure store used as a database, cache, and message broker.
type: application
version: 0.20.6
appVersion: "7.2.0"
keywords:
  - redis
  - database
  - cache
  - in-memory
  - key-value
  - nosql
home: https://www.redis.io
sources:
  - https://github.com/cisco-ai-defense/ai-defense-hybrid/tree/main/charts/redis
icon: https://a.storyblok.com/f/143071/512x512/32c74816d1/redis-logo.svg
annotations:
  license: Apache-2.0